### ISSUE TITLE
Bumping NETC-55

### ISSUE THREAD

**Issue by rdev5** [Jasig/dotnet-cas-client#24]
References:
* https://issues.jasig.org/browse/NETC-55
* http://jasig.275507.n4.nabble.com/Apparent-bug-found-in-NET-CAS-client-bypassCasForHandlers-setting-td4661276.html

Has anything been done on these? It also appears that the current Wiki does not describe any information concerning bypassCasForHandlers.

**Comment by mmoayyed** [comment]
Don't think so. 

If you could submit a PR, that would be welcome.

**Comment by rdev5** [comment]
Sure - I need to finish debugging #25 and probably roll this into that PR when ready.

Thanks
