### ISSUE TITLE
Configure CAS client programmatically

### ISSUE THREAD

**Issue by guybe1977** [Jasig/dotnet-cas-client#27]
I need to configure the CAS client in run-time in order to allow multiple configurations for multiple environments. As I couldn't find a way to configure the CAS client besides changing the web.config, my current solution is to rewrite the web.config upon web application start.

I was wondering if there is another way to do it or if there is an intention to add a way to configure the client programmatically.

**Comment by mmoayyed** [comment]
post to the cas user mailing list please
